  # Install control plane
  - kubeadm init --config /etc/kubernetes/kubeadm-config.yaml

  # Configure kubectl for root
  - export HOME=/root
  - mkdir -p $HOME/.kube
  - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

  # Configure kubectl for almalinux with autocomplete and alias
  - mkdir -p /home/almalinux/.kube
  - cp -i /etc/kubernetes/admin.conf /home/almalinux/.kube/config
  - chown almalinux:almalinux /home/almalinux/.kube/config
  - echo "source <(kubectl completion bash)" >> /home/almalinux/.bashrc
  - echo "alias k=kubectl" >> /home/almalinux/.bashrc
  - echo "complete -o default -F __start_kubectl k" >> /home/almalinux/.bashrc

  # Install calico (cri)
  - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/tigera-operator.yaml
  - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/custom-resources.yaml

  # Install ingress
  - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/baremetal/deploy.yaml